CREATE TABLE SALES  (
REGION VARCHAR(250) NOT NULL,
COUNTRY VARCHAR(250) NOT NULL,
ITEM_TYPE VARCHAR(250) NOT NULL,
SALES_CHANNEL VARCHAR(250) NOT NULL,
ORDER_PRIORITY VARCHAR(2) NOT NULL,
ORDER_DATE DATETIME NOT NULL,
ORDER_ID VARCHAR(250) NOT NULL,
SHIP_DATE DATETIME NOT NULL,
UNITS_SOLD DECIMAL(13, 4),
UNIT_PRICE DECIMAL(13, 4),
UNIT_COST DECIMAL(13, 4),
TOTAL_REVENUE DECIMAL(13, 4),
TOTAL_COST DECIMAL(13, 4),
TOTAL_PROFIT DECIMAL(13, 4)
 );
